name: "Víctor Fernández"
description: "Front-end developer and designer"
url: "http://localhost:4000"
paginate: 10
markdown: maruku
permalink: /:year/:month/:title
pygments: true
destination: public

navigation:
- text: Writing
  url: /writing
- text: Pictures
  url: /pictures
- text: Projects
  url: /projects
- text: Colophon
  url: /colophon