name: "Víctor Fernández"
tagline: "Front-end developer and designer"
description: "Víctor Fernández is a designer and web developer from Venezuela, currently working for R/GA Buenos Aires. This is his personal website."

url: "http://localhost:4000"
paginate: 10
markdown: maruku
permalink: /:year/:month/:title
pygments: true
exclude: [node_modules, Gruntfile.js, package.json, README.md]
destination: public

navigation:
- text: Writing
  url: /
- text: Projects
  url: /projects
- text: About
  url: /about

social:
- name: Twitter
  url: http://twitter.com/vctrfrnndz
- name: Github
  url: http://github.com/vctrfrnndz
- name: Dribbble
  url: http://dribbble.com/vctrfrnndz
