name: "Víctor Fernández"
description: "Front-end developer and designer"
url: "http://localhost:4000"
paginate: 10
markdown: maruku
permalink: /:year/:month/:title
pygments: true
exclude: [node_modules, Gruntfile.js, package.json, README.md]
destination: public

navigation:
- text: Writing
  url: /
- text: Pictures
  url: /pictures
- text: Projects
  url: /projects
- text: Colophon
  url: /colophon

social:
- name: Twitter
  url: http://twitter.com/vctrfrnndz
- name: Github
  url: http://github.com/vctrfrnndz
- name: Dribbble
  url: http://dribbble.com/vctrfrnndz
